---
ansible_user: dudin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

# Общие настройки
timezone: Europe/Moscow

# Настройки nginx
nginx_worker_processes: auto
nginx_worker_connections: 768

# Настройки ELK
elasticsearch_version: "8.8.0"
kibana_version: "8.8.0"
elasticsearch_cluster_name: "diplom-cluster"
elasticsearch_heap_size: "4g"

java_version: "17"

kibana_server_host: "0.0.0.0"
kibana_server_port: 5601

es_group_name: "elk"
es_host_in_inventory: "{{ groups[es_group_name] | first }}"
es_private_ip: "{{ hostvars[es_host_in_inventory].ansible_host | default(groups[es_group_name] | first) }}"

es_scheme: "http"
kibana_xpack_security_enabled: false
kibana_encryption_key: "at_least_32_characters_long_key_here_12345"

# Отключаем уведомление об интерпретаторе
ansible_python_interpreter: /usr/bin/python3

# Настройки Zabbix сервера
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: zabbix
zabbix_db_host: "127.0.0.1"
zabbix_db_port: 5432

php_version: "8.1"
php_timezone: "Europe/Moscow"

postgres_version: "14"
pg_hba_path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"

zabbix_release_deb_url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"

zabbix_packages:
  - apache2
  - postgresql
  - zabbix-server-pgsql
  - zabbix-frontend-php
  - "php{{ php_version }}-pgsql"
  - zabbix-apache-conf
  - zabbix-sql-scripts
  - zabbix-agent

# Настройки Zabbix агента
zabbix_agent_server: "zabbix.ru-central1.internal"
zabbix_agent_serveractive: "zabbix.ru-central1.internal"
zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_version: "6.4"