---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create web root directory
  file:
    path: /var/www/html/
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart nginx

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart nginx

- name: Enable and start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes